### ISSUE TITLE
STORY: Home page

### ISSUE THREAD

**Issue by Erikas-Ramanauskas** [Erikas-Ramanauskas/Project-Cauldron#1]
## Description:
As a first-time user, I want to see the home page so that I can quickly understand the purpose of the site

### Tasks:
- [ ] Basic HTML structure
- [ ] Background image/css
- [ ] Buttons: `Start Game`, `How to play`
- [ ] Style
