### ISSUE TITLE
USER STORY: Ingredients

### ISSUE THREAD

**Issue by pavlo-myskov** [Erikas-Ramanauskas/Project-Cauldron#22]
### Description:

As a player, I want to see the ingredients so that I can know what I need to collect

### Tasks:
- [x] Generate ingredient images
- [x] Separate images from background
- [x] Add images to the game board 
- [x] #17
