### ISSUE TITLE
USER STORY: Sound Interactions

### ISSUE THREAD

**Issue by pavlo-myskov** [Erikas-Ramanauskas/Project-Cauldron#35]
### Description:

As a player, I want to get all interaction feedback in the form of sound so that I can feel more immersed in the game

### Tasks:
_At least a few different sounds for main actions_
- [ ] Background music to the game
- [ ] Music to the game fight
- [x] Sound effect(s) to the game potion making
- [ ] Sound effect to the win fight
- [ ] Sound effect to the lose fight
- [ ] Music to the game win screen
- [ ] Music to the game over screen
