### ISSUE TITLE
USER STORY: Game Board navigation 

### ISSUE THREAD

**Issue by pavlo-myskov** [Erikas-Ramanauskas/Project-Cauldron#76]
### Description:

As a player I want to be able to navigate to the kitchen, so that I can expore and create new potions

### Tasks:
- [x] Add collapsible navbar with links/buttons to the game board, so that user have access to the kitchen and home page menu
- [x] Add kitchen btn link
- [x] Add main menu btn link
